// sample-code/vue/uploads-table.vue
<script>
import { UploadsListProviderInjectionKey } from '@w3ui/vue-uploads-list'

export default {
  inject: {
    loading: { from: UploadsListProviderInjectionKey.loading },
    data: { from: UploadsListProviderInjectionKey.data },
    error: { from: UploadsListProviderInjectionKey.error },
    reload: { from: UploadsListProviderInjectionKey.reload }
  }
}
</script>
<template>
  <div v-if="error == null">
    <div v-if="data && data.results.length">
      <table>
        <thead>
          <tr>
            <th>Data CID</th>
            <th>CAR CID</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="upload in data.results">
            <td>{{upload.dataCid}}</td>
            <td>{{upload.carCids[0]}}</td>
            <td>{{upload.uploadedAt.toLocaleString()}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <p v-else>No uploads</p>
    <button type="button" @click="reload">Refresh</button>
    <p v-if="loading">Loading...</p>
  </div>
  <div v-else>
    <h1>⚠️ Error: failed to list uploads: {{error.message}}</h1>
    <p>Check the browser console for details.</p>
  </div>
</template>

// sample-code/react/uploads-table.jsx
import React from 'react'
import { useUploadsList } from '@w3ui/react-uploads-list'

export default function Component () {
  const { loading, data, error, reload } = useUploadsList()
  if (error) return <p>⚠️ {err.message}</p>

  return (
    <div>
      {data && data.results.length
        ? (
          <table>
            <thead>
              <tr>
                <th>Data CID</th>
                <th>CAR CID</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {data.results.map(({ dataCid, carCids, uploadedAt }) => (
                <tr key={dataCid}>
                  <td>{dataCid}</td>
                  <td>{carCids[0]}</td>
                  <td>{uploadedAt.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          )
        : <p>No uploads</p>}
      <button type='button' onClick={reload}>🔄 Refresh</button>
      {loading ? <p>Loading...</p> : null}
    </div>
  )
}
