// sample-code/solid/uploads-table.js
import { Switch, Match } from 'solid-js'
import { useKeyring } from '@w3ui/solid-keyring'
import { createUploadsListResource } from '@w3ui/solid-uploads-list'

export default function Component () {
  const [keyringState, keyringActions] = useKeyring()
  const [data, { refetch }] = createUploadsListResource(() => ({...keyringState, ...keyringActions}), { initialValue: { results: [] } })

  return (
    <div>
      <Switch>
        <Match when={data.state === 'errored'}>
          <p>⚠️ {err.message}</p> 
        </Match>
        <Match when={data.state === 'ready'}>
          {data().results.length
            ? (
              <div>
                <table>
                  <thead>
                    <tr>
                      <th>Data CID</th>
                      <th>CAR CID</th>
                      <th>Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {data().results.map(({ dataCid, carCids, uploadedAt }) => (
                      <tr key={dataCid}>
                        <td>{dataCid}</td>
                        <td>{carCids[0]}</td>
                        <td>{uploadedAt.toLocaleString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              )
            : <p>No uploads</p>}
        </Match>
      </Switch>
      <button type='button' onClick={refetch}>Refresh</button>
      {data.loading ? <p>Loading...</p> : null}
    </div>
  )
}

// sample-code/react/uploads-table.jsx
import React from 'react'
import { useUploadsList } from '@w3ui/react-uploads-list'

export default function Component () {
  const { loading, data, error, reload } = useUploadsList()
  if (error) return <p>⚠️ {err.message}</p>

  return (
    <div>
      {data && data.results.length
        ? (
          <table>
            <thead>
              <tr>
                <th>Data CID</th>
                <th>CAR CID</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {data.results.map(({ dataCid, carCids, uploadedAt }) => (
                <tr key={dataCid}>
                  <td>{dataCid}</td>
                  <td>{carCids[0]}</td>
                  <td>{uploadedAt.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          )
        : <p>No uploads</p>}
      <button type='button' onClick={reload}>🔄 Refresh</button>
      {loading ? <p>Loading...</p> : null}
    </div>
  )
}
